/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: marisa_swig.swigcxx_

package marisa

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef _gostring_ swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
typedef long long swig_type_23;
typedef long long swig_type_24;
typedef long long swig_type_25;
extern void _wrap_Swig_free_marisa_2116d121546c47ae(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_marisa_2116d121546c47ae(swig_intgo arg1);
extern swig_intgo _wrap_OK_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_STATE_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_NULL_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_BOUND_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_RANGE_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_CODE_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_RESET_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_SIZE_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_MEMORY_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_IO_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_FORMAT_ERROR_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_MIN_NUM_TRIES_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_MAX_NUM_TRIES_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_DEFAULT_NUM_TRIES_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_HUGE_CACHE_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_LARGE_CACHE_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_NORMAL_CACHE_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_SMALL_CACHE_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_TINY_CACHE_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_DEFAULT_CACHE_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_TEXT_TAIL_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_BINARY_TAIL_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_DEFAULT_TAIL_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_LABEL_ORDER_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_WEIGHT_ORDER_marisa_2116d121546c47ae(void);
extern swig_intgo _wrap_DEFAULT_ORDER_marisa_2116d121546c47ae(void);
extern swig_type_1 _wrap_Key_str_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_type_2 _wrap_Key_id_marisa_2116d121546c47ae(uintptr_t arg1);
extern float _wrap_Key_weight_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_delete_Key_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Query_str_marisa_2116d121546c47ae(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3);
extern swig_type_3 _wrap_Query_id_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_delete_Query_marisa_2116d121546c47ae(uintptr_t arg1);
extern uintptr_t _wrap_new_Keyset_marisa_2116d121546c47ae(void);
extern void _wrap_delete_Keyset_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Keyset_pushBack_marisa_2116d121546c47ae(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_Keyset_pushBackStringWithWeight_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_4 arg2, float arg3);
extern void _wrap_Keyset_pushBackString_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_5 arg2);
extern uintptr_t _wrap_Keyset_key_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_6 arg2);
extern void _wrap_Keyset_keyStr_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_7 arg2, swig_voidp arg3, swig_voidp arg4);
extern swig_type_8 _wrap_Keyset_keyId_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_9 arg2);
extern swig_type_10 _wrap_Keyset_numKeys_marisa_2116d121546c47ae(uintptr_t arg1);
extern _Bool _wrap_Keyset_empty_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_type_11 _wrap_Keyset_size_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_type_12 _wrap_Keyset_totalLength_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Keyset_reset_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Keyset_clear_marisa_2116d121546c47ae(uintptr_t arg1);
extern uintptr_t _wrap_new_Agent_marisa_2116d121546c47ae(void);
extern void _wrap_delete_Agent_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Agent_setQueryString_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_13 arg2);
extern void _wrap_Agent_setQuery_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_14 arg2);
extern uintptr_t _wrap_Agent_key_marisa_2116d121546c47ae(uintptr_t arg1);
extern uintptr_t _wrap_Agent_query_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Agent_keyStr_marisa_2116d121546c47ae(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3);
extern swig_type_15 _wrap_Agent_keyId_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Agent_queryStr_marisa_2116d121546c47ae(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3);
extern swig_type_16 _wrap_Agent_queryId_marisa_2116d121546c47ae(uintptr_t arg1);
extern uintptr_t _wrap_new_Trie_marisa_2116d121546c47ae(void);
extern void _wrap_delete_Trie_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Trie_build__SWIG_0_marisa_2116d121546c47ae(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern void _wrap_Trie_build__SWIG_1_marisa_2116d121546c47ae(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_Trie_mmap_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_17 arg2);
extern void _wrap_Trie_load_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_18 arg2);
extern void _wrap_Trie_save_marisa_2116d121546c47ae(uintptr_t arg1, swig_type_19 arg2);
extern _Bool _wrap_Trie_lookup_marisa_2116d121546c47ae(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_Trie_reverseLookup_marisa_2116d121546c47ae(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_Trie_commonPrefixSearch_marisa_2116d121546c47ae(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_Trie_predictiveSearch_marisa_2116d121546c47ae(uintptr_t arg1, uintptr_t arg2);
extern swig_type_20 _wrap_Trie_numTries_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_type_21 _wrap_Trie_numKeys_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_type_22 _wrap_Trie_numNodes_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_intgo _wrap_Trie_tailNode_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_intgo _wrap_Trie_nodeOrder_marisa_2116d121546c47ae(uintptr_t arg1);
extern _Bool _wrap_Trie_empty_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_type_23 _wrap_Trie_size_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_type_24 _wrap_Trie_totalSize_marisa_2116d121546c47ae(uintptr_t arg1);
extern swig_type_25 _wrap_Trie_ioSize_marisa_2116d121546c47ae(uintptr_t arg1);
extern void _wrap_Trie_clear_marisa_2116d121546c47ae(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_marisa_2116d121546c47ae(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Marisa_swigErrorCode int
func _swig_getOK() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_OK_marisa_2116d121546c47ae())
	return swig_r
}

var OK Marisa_swigErrorCode = _swig_getOK()
func _swig_getSTATE_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_STATE_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var STATE_ERROR Marisa_swigErrorCode = _swig_getSTATE_ERROR()
func _swig_getNULL_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_NULL_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var NULL_ERROR Marisa_swigErrorCode = _swig_getNULL_ERROR()
func _swig_getBOUND_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_BOUND_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var BOUND_ERROR Marisa_swigErrorCode = _swig_getBOUND_ERROR()
func _swig_getRANGE_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_RANGE_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var RANGE_ERROR Marisa_swigErrorCode = _swig_getRANGE_ERROR()
func _swig_getCODE_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_CODE_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var CODE_ERROR Marisa_swigErrorCode = _swig_getCODE_ERROR()
func _swig_getRESET_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_RESET_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var RESET_ERROR Marisa_swigErrorCode = _swig_getRESET_ERROR()
func _swig_getSIZE_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_SIZE_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var SIZE_ERROR Marisa_swigErrorCode = _swig_getSIZE_ERROR()
func _swig_getMEMORY_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_MEMORY_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var MEMORY_ERROR Marisa_swigErrorCode = _swig_getMEMORY_ERROR()
func _swig_getIO_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_IO_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var IO_ERROR Marisa_swigErrorCode = _swig_getIO_ERROR()
func _swig_getFORMAT_ERROR() (_swig_ret Marisa_swigErrorCode) {
	var swig_r Marisa_swigErrorCode
	swig_r = (Marisa_swigErrorCode)(C._wrap_FORMAT_ERROR_marisa_2116d121546c47ae())
	return swig_r
}

var FORMAT_ERROR Marisa_swigErrorCode = _swig_getFORMAT_ERROR()
type Marisa_swigNumTries int
func _swig_getMIN_NUM_TRIES() (_swig_ret Marisa_swigNumTries) {
	var swig_r Marisa_swigNumTries
	swig_r = (Marisa_swigNumTries)(C._wrap_MIN_NUM_TRIES_marisa_2116d121546c47ae())
	return swig_r
}

var MIN_NUM_TRIES Marisa_swigNumTries = _swig_getMIN_NUM_TRIES()
func _swig_getMAX_NUM_TRIES() (_swig_ret Marisa_swigNumTries) {
	var swig_r Marisa_swigNumTries
	swig_r = (Marisa_swigNumTries)(C._wrap_MAX_NUM_TRIES_marisa_2116d121546c47ae())
	return swig_r
}

var MAX_NUM_TRIES Marisa_swigNumTries = _swig_getMAX_NUM_TRIES()
func _swig_getDEFAULT_NUM_TRIES() (_swig_ret Marisa_swigNumTries) {
	var swig_r Marisa_swigNumTries
	swig_r = (Marisa_swigNumTries)(C._wrap_DEFAULT_NUM_TRIES_marisa_2116d121546c47ae())
	return swig_r
}

var DEFAULT_NUM_TRIES Marisa_swigNumTries = _swig_getDEFAULT_NUM_TRIES()
type Marisa_swigCacheLevel int
func _swig_getHUGE_CACHE() (_swig_ret Marisa_swigCacheLevel) {
	var swig_r Marisa_swigCacheLevel
	swig_r = (Marisa_swigCacheLevel)(C._wrap_HUGE_CACHE_marisa_2116d121546c47ae())
	return swig_r
}

var HUGE_CACHE Marisa_swigCacheLevel = _swig_getHUGE_CACHE()
func _swig_getLARGE_CACHE() (_swig_ret Marisa_swigCacheLevel) {
	var swig_r Marisa_swigCacheLevel
	swig_r = (Marisa_swigCacheLevel)(C._wrap_LARGE_CACHE_marisa_2116d121546c47ae())
	return swig_r
}

var LARGE_CACHE Marisa_swigCacheLevel = _swig_getLARGE_CACHE()
func _swig_getNORMAL_CACHE() (_swig_ret Marisa_swigCacheLevel) {
	var swig_r Marisa_swigCacheLevel
	swig_r = (Marisa_swigCacheLevel)(C._wrap_NORMAL_CACHE_marisa_2116d121546c47ae())
	return swig_r
}

var NORMAL_CACHE Marisa_swigCacheLevel = _swig_getNORMAL_CACHE()
func _swig_getSMALL_CACHE() (_swig_ret Marisa_swigCacheLevel) {
	var swig_r Marisa_swigCacheLevel
	swig_r = (Marisa_swigCacheLevel)(C._wrap_SMALL_CACHE_marisa_2116d121546c47ae())
	return swig_r
}

var SMALL_CACHE Marisa_swigCacheLevel = _swig_getSMALL_CACHE()
func _swig_getTINY_CACHE() (_swig_ret Marisa_swigCacheLevel) {
	var swig_r Marisa_swigCacheLevel
	swig_r = (Marisa_swigCacheLevel)(C._wrap_TINY_CACHE_marisa_2116d121546c47ae())
	return swig_r
}

var TINY_CACHE Marisa_swigCacheLevel = _swig_getTINY_CACHE()
func _swig_getDEFAULT_CACHE() (_swig_ret Marisa_swigCacheLevel) {
	var swig_r Marisa_swigCacheLevel
	swig_r = (Marisa_swigCacheLevel)(C._wrap_DEFAULT_CACHE_marisa_2116d121546c47ae())
	return swig_r
}

var DEFAULT_CACHE Marisa_swigCacheLevel = _swig_getDEFAULT_CACHE()
type Marisa_swigTailMode int
func _swig_getTEXT_TAIL() (_swig_ret Marisa_swigTailMode) {
	var swig_r Marisa_swigTailMode
	swig_r = (Marisa_swigTailMode)(C._wrap_TEXT_TAIL_marisa_2116d121546c47ae())
	return swig_r
}

var TEXT_TAIL Marisa_swigTailMode = _swig_getTEXT_TAIL()
func _swig_getBINARY_TAIL() (_swig_ret Marisa_swigTailMode) {
	var swig_r Marisa_swigTailMode
	swig_r = (Marisa_swigTailMode)(C._wrap_BINARY_TAIL_marisa_2116d121546c47ae())
	return swig_r
}

var BINARY_TAIL Marisa_swigTailMode = _swig_getBINARY_TAIL()
func _swig_getDEFAULT_TAIL() (_swig_ret Marisa_swigTailMode) {
	var swig_r Marisa_swigTailMode
	swig_r = (Marisa_swigTailMode)(C._wrap_DEFAULT_TAIL_marisa_2116d121546c47ae())
	return swig_r
}

var DEFAULT_TAIL Marisa_swigTailMode = _swig_getDEFAULT_TAIL()
type Marisa_swigNodeOrder int
func _swig_getLABEL_ORDER() (_swig_ret Marisa_swigNodeOrder) {
	var swig_r Marisa_swigNodeOrder
	swig_r = (Marisa_swigNodeOrder)(C._wrap_LABEL_ORDER_marisa_2116d121546c47ae())
	return swig_r
}

var LABEL_ORDER Marisa_swigNodeOrder = _swig_getLABEL_ORDER()
func _swig_getWEIGHT_ORDER() (_swig_ret Marisa_swigNodeOrder) {
	var swig_r Marisa_swigNodeOrder
	swig_r = (Marisa_swigNodeOrder)(C._wrap_WEIGHT_ORDER_marisa_2116d121546c47ae())
	return swig_r
}

var WEIGHT_ORDER Marisa_swigNodeOrder = _swig_getWEIGHT_ORDER()
func _swig_getDEFAULT_ORDER() (_swig_ret Marisa_swigNodeOrder) {
	var swig_r Marisa_swigNodeOrder
	swig_r = (Marisa_swigNodeOrder)(C._wrap_DEFAULT_ORDER_marisa_2116d121546c47ae())
	return swig_r
}

var DEFAULT_ORDER Marisa_swigNodeOrder = _swig_getDEFAULT_ORDER()
type SwigcptrKey uintptr

func (p SwigcptrKey) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrKey) SwigIsKey() {
}

func (arg1 SwigcptrKey) Str() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_Key_str_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrKey) Id() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Key_id_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrKey) Weight() (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1
	swig_r = (float32)(C._wrap_Key_weight_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteKey(arg1 Key) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Key_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

type Key interface {
	Swigcptr() uintptr
	SwigIsKey()
	Str() (_swig_ret string)
	Id() (_swig_ret int64)
	Weight() (_swig_ret float32)
}

type SwigcptrQuery uintptr

func (p SwigcptrQuery) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrQuery) SwigIsQuery() {
}

func (arg1 SwigcptrQuery) Str(arg2 *string, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Query_str_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrQuery) Id() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Query_id_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeleteQuery(arg1 Query) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Query_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

type Query interface {
	Swigcptr() uintptr
	SwigIsQuery()
	Str(arg2 *string, arg3 *int64)
	Id() (_swig_ret int64)
}

type SwigcptrKeyset uintptr

func (p SwigcptrKeyset) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrKeyset) SwigIsKeyset() {
}

func NewKeyset() (_swig_ret Keyset) {
	var swig_r Keyset
	swig_r = (Keyset)(SwigcptrKeyset(C._wrap_new_Keyset_marisa_2116d121546c47ae()))
	return swig_r
}

func DeleteKeyset(arg1 Keyset) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Keyset_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrKeyset) PushBack(arg2 Marisa_Key) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Keyset_pushBack_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrKeyset) PushBackStringWithWeight(arg2 string, arg3 float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Keyset_pushBackStringWithWeight_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)), C.float(_swig_i_2))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrKeyset) PushBackString(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Keyset_pushBackString_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrKeyset) Key(arg2 int64) (_swig_ret Key) {
	var swig_r Key
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Key)(SwigcptrKey(C._wrap_Keyset_key_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.swig_type_6(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrKeyset) KeyStr(arg2 int64, arg3 *string, arg4 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_Keyset_keyStr_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.swig_type_7(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3))
}

func (arg1 SwigcptrKeyset) KeyId(arg2 int64) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_Keyset_keyId_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.swig_type_9(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrKeyset) NumKeys() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Keyset_numKeys_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrKeyset) Empty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Keyset_empty_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrKeyset) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Keyset_size_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrKeyset) TotalLength() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Keyset_totalLength_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrKeyset) Reset() {
	_swig_i_0 := arg1
	C._wrap_Keyset_reset_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrKeyset) Clear() {
	_swig_i_0 := arg1
	C._wrap_Keyset_clear_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

type Keyset interface {
	Swigcptr() uintptr
	SwigIsKeyset()
	PushBack(arg2 Marisa_Key)
	PushBackStringWithWeight(arg2 string, arg3 float32)
	PushBackString(arg2 string)
	Key(arg2 int64) (_swig_ret Key)
	KeyStr(arg2 int64, arg3 *string, arg4 *int64)
	KeyId(arg2 int64) (_swig_ret int64)
	NumKeys() (_swig_ret int64)
	Empty() (_swig_ret bool)
	Size() (_swig_ret int64)
	TotalLength() (_swig_ret int64)
	Reset()
	Clear()
}

type SwigcptrAgent uintptr

func (p SwigcptrAgent) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAgent) SwigIsAgent() {
}

func NewAgent() (_swig_ret Agent) {
	var swig_r Agent
	swig_r = (Agent)(SwigcptrAgent(C._wrap_new_Agent_marisa_2116d121546c47ae()))
	return swig_r
}

func DeleteAgent(arg1 Agent) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Agent_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrAgent) SetQueryString(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Agent_setQueryString_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrAgent) SetQuery(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Agent_setQuery_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.swig_type_14(_swig_i_1))
}

func (arg1 SwigcptrAgent) Key() (_swig_ret Key) {
	var swig_r Key
	_swig_i_0 := arg1
	swig_r = (Key)(SwigcptrKey(C._wrap_Agent_key_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAgent) Query() (_swig_ret Query) {
	var swig_r Query
	_swig_i_0 := arg1
	swig_r = (Query)(SwigcptrQuery(C._wrap_Agent_query_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrAgent) KeyStr(arg2 *string, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Agent_keyStr_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrAgent) KeyId() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Agent_keyId_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrAgent) QueryStr(arg2 *string, arg3 *int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_Agent_queryStr_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2))
}

func (arg1 SwigcptrAgent) QueryId() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Agent_queryId_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type Agent interface {
	Swigcptr() uintptr
	SwigIsAgent()
	SetQueryString(arg2 string)
	SetQuery(arg2 int64)
	Key() (_swig_ret Key)
	Query() (_swig_ret Query)
	KeyStr(arg2 *string, arg3 *int64)
	KeyId() (_swig_ret int64)
	QueryStr(arg2 *string, arg3 *int64)
	QueryId() (_swig_ret int64)
}

type SwigcptrTrie uintptr

func (p SwigcptrTrie) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTrie) SwigIsTrie() {
}

func NewTrie() (_swig_ret Trie) {
	var swig_r Trie
	swig_r = (Trie)(SwigcptrTrie(C._wrap_new_Trie_marisa_2116d121546c47ae()))
	return swig_r
}

func DeleteTrie(arg1 Trie) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Trie_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrTrie) Build__SWIG_0(arg2 Keyset, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_Trie_build__SWIG_0_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2))
}

func (arg1 SwigcptrTrie) Build__SWIG_1(arg2 Keyset) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Trie_build__SWIG_1_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (p SwigcptrTrie) Build(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		p.Build__SWIG_1(a[0].(Keyset))
		return
	}
	if argc == 2 {
		p.Build__SWIG_0(a[0].(Keyset), a[1].(int))
		return
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrTrie) Mmap(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Trie_mmap_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrTrie) Load(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Trie_load_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), *(*C.swig_type_18)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrTrie) Save(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Trie_save_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), *(*C.swig_type_19)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrTrie) Lookup(arg2 Agent) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_Trie_lookup_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrTrie) ReverseLookup(arg2 Agent) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_Trie_reverseLookup_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrTrie) CommonPrefixSearch(arg2 Agent) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_Trie_commonPrefixSearch_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrTrie) PredictiveSearch(arg2 Agent) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_Trie_predictiveSearch_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrTrie) NumTries() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Trie_numTries_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) NumKeys() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Trie_numKeys_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) NumNodes() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Trie_numNodes_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) TailNode() (_swig_ret Marisa_swigTailMode) {
	var swig_r Marisa_swigTailMode
	_swig_i_0 := arg1
	swig_r = (Marisa_swigTailMode)(C._wrap_Trie_tailNode_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) NodeOrder() (_swig_ret Marisa_swigNodeOrder) {
	var swig_r Marisa_swigNodeOrder
	_swig_i_0 := arg1
	swig_r = (Marisa_swigNodeOrder)(C._wrap_Trie_nodeOrder_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) Empty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_Trie_empty_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Trie_size_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) TotalSize() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Trie_totalSize_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) IoSize() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_Trie_ioSize_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTrie) Clear() {
	_swig_i_0 := arg1
	C._wrap_Trie_clear_marisa_2116d121546c47ae(C.uintptr_t(_swig_i_0))
}

type Trie interface {
	Swigcptr() uintptr
	SwigIsTrie()
	Build(a ...interface{})
	Mmap(arg2 string)
	Load(arg2 string)
	Save(arg2 string)
	Lookup(arg2 Agent) (_swig_ret bool)
	ReverseLookup(arg2 Agent)
	CommonPrefixSearch(arg2 Agent) (_swig_ret bool)
	PredictiveSearch(arg2 Agent) (_swig_ret bool)
	NumTries() (_swig_ret int64)
	NumKeys() (_swig_ret int64)
	NumNodes() (_swig_ret int64)
	TailNode() (_swig_ret Marisa_swigTailMode)
	NodeOrder() (_swig_ret Marisa_swigNodeOrder)
	Empty() (_swig_ret bool)
	Size() (_swig_ret int64)
	TotalSize() (_swig_ret int64)
	IoSize() (_swig_ret int64)
	Clear()
}


type SwigcptrMarisa_Key uintptr
type Marisa_Key interface {
	Swigcptr() uintptr;
}
func (p SwigcptrMarisa_Key) Swigcptr() uintptr {
	return uintptr(p)
}

